[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
linker = "x86_64-unknown-linux-gnu-ld"
runner = "./.cargo/run.nu"
rustflags = [
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
    "-C", "target-feature=-sse,-sse2"
]
